version: '2'

services:
  mysql:
    image: docker.io/bitnami/mysql:8.0
    ports:
      - '3306:3306'
    volumes:
      - ./data/application:/docker-entrypoint-initdb.d
      - ./mysql_data:/var/lib/mysql
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
  stoke-market:
    build: .
    image: stoke-market:1.0
    container_name: stoke-market
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://
        mysql:3306/stock_market
      SPRING_DATASOURCE_USERNAME: root
    links:
      - mysql
volumes:
  mysql_data:
    driver: local
networks:
  common-network:
    driver: bridge
