spring:
  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    password: password
    url:  jdbc:h2:mem:mydb
  jpa:
    database: h2
    defer-datasource-initialization: true
    hibernate:
      use-new-id-generator-mappings: false
springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false