spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password:
    url:  ${SPRING_DATASOURCE_URL=jdbc:jdbc:mysql://localhost:3306/stock_market}
  jpa:
    hibernate:
      ddl-auto: create-drop
    database: mysql
springdoc:
  swagger-ui:
    path: /swagger-ui.html